apiVersion: v1
kind: Service
metadata:
  labels:
    app: leantime
  name: leantime
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: "8080"
  type: NodePort
  selector:
    app: leantime
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leantime
  name: leantime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leantime
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: leantime
    spec:
      containers:
        - env:
            - name: LEAN_DB_DATABASE
              value: leantime
            - name: LEAN_DB_HOST
              value: 172.17.0.5
            - name: LEAN_DB_PASSWORD
              value: 321.qwerty
            - name: LEAN_DB_USER
              value: admin
            - name: LEAN_DEFAULT_TIMEZONE
              value: Europe/Stockholm
            - name: LEAN_SESSION_EXPIRATION
              value: "28800"
            - name: LEAN_SESSION_PASSWORD
              value: GD8Fozemg3AqM9my86TTfgTeGPXXkPF7
            - name: LEAN_SITENAME
              value: Leantime
          image: leantime/leantime:latest
          name: leantime
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html/public/userfiles
              name: public-userfiles
            - mountPath: /var/www/html/userfiles
              name: userfiles
      restartPolicy: Always
      volumes:
        - name: public-userfiles
          persistentVolumeClaim:
            claimName: public-userfiles
        - name: userfiles
          persistentVolumeClaim:
            claimName: userfiles
status: {}
