apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: leantime-db
    tier: backend
  ports:
    - name: "3306"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leantime-db
  name: leantime-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leantime-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: leantime-db
    spec:
      containers:
        - args:
            - --character-set-server=utf8
            - --collation-server=utf8_unicode_ci
          env:
            - name: MYSQL_DATABASE
              value: leantime
            - name: MYSQL_PASSWORD
              value: 321.qwerty
            - name: MYSQL_ROOT_PASSWORD
              value: 321.qwerty
            - name: MYSQL_USER
              value: admin
          image: mysql:8.0
          name: mysql-leantime
          resources: {}
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      restartPolicy: Always
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

status: {}
